#!/bin/sh
# download and build autotools and bootstrap a Xapian SVN tree with them.
#
# Copyright (C) 2008 Olly Betts
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
# USA

trap 'echo "$0 failed"' EXIT
set -e

curdir=`pwd`

# cd to srcdir if we aren't already there.
srcdir=`echo "$0"|sed 's!/*[^/]*$!!'`
case $srcdir in
  ""|.)
    srcdir=. ;;
  *)
    cd "$srcdir" ;;
esac

if [ "$1" = "--clean" ] ; then
  rm -rf INST BUILD
fi

test -d INST || mkdir INST
instdir=`pwd`/INST

test -d BUILD || mkdir BUILD
cd BUILD

do_build_if_required() {
  package=$1
  basename=$package-$2
  checksum=$3
  tarball=$basename.tar.bz2
  if [ "$basename" = "libtool-1.5.26" ] ; then
    tarball=$basename.tar.gz
  fi
  stamp=$package.stamp

  # Download the tarball if required.
  if [ ! -f "$tarball" ] ; then
    wget "ftp://ftp.gnu.org/gnu/$package/$tarball"
  fi

  if [ -f "$stamp" ] ; then
    find_stdout=`find "$stamp" -newer "$tarball" -print`
  else
    find_stdout=
  fi

  if [ -z "$find_stdout" ] ; then
    # Verify tarball's checksum.
    echo "$checksum  $tarball"|sha1sum -c

    for f in "$package"-* ; do
      [ "$f" = "$tarball" ] || rm -rf "$f"
    done

    case $tarball in
    *.bz2)
      bzip2 -dc "$tarball"| tar xf - ;;
    *)
      gzip -dc "$tarball"| tar xf - ;;
    esac

    cd "$basename"
    ./configure --prefix="$instdir"
    make
    make install
    cd ..
    rm -rf "$basename"

    touch "$stamp"
  fi
}

do_build_if_required autoconf 2.62 de2b6f57da07427794c56e25844e31f35fc46755
do_build_if_required automake 1.10.1 cd2e0f7054d4edc75cbf87cd8a92962b3b417b74
do_build_if_required libtool 1.5.26 4c1738351736562a951a345e24f233d00953ec0a

for t in autoreconf autoconf autoheader autom4te automake aclocal libtoolize
do
   var=`echo "$t"|tr a-z A-Z`
   eval "$var=\"\$instdir\"/bin/$t;export $var"
done

trap - EXIT

cd "$curdir"
exec "$srcdir/bootstrap"
