#!/bin/sh
# build autotools and bootstrap a Xapian SVN tree with them.
#
# Copyright (C) 2008 Olly Betts
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
# USA

trap 'echo "$0 failed"' EXIT
set -e

rm -rf INST BUILD
mkdir INST BUILD

instdir=`pwd`/INST
for subdir in autoconf automake libtool ; do
    mkdir BUILD/"$subdir"
    cd BUILD/"$subdir"
    ../../"$subdir"/configure --prefix="$instdir"
    make
    make install
    cd ../..
done

for tool in autoreconf autoconf autoheader autom4te automake aclocal libtoolize ; do
   var=`echo "$tool"|tr a-z A-Z`
   eval "$var=\"\$instdir\"/bin/$tool;export $var"
done

trap - EXIT

exec ./bootstrap
