#!/bin/sh
set -e

REPOS=${1-xapian-core xapian-bindings xapian-omega}

# Packaging branch
BRANCH=1.3

# Repo base
REPO_BASE=ssh://olly@git.debian.org/git/collab-maint

here=`pwd`
for r in $REPOS ; do
    case $r in
	xapian-omega) d=xapian-applications/omega ;;
	*) d=$r;;
    esac
    cd "$d"
    # FIXME: check for changes in debian first...
    rm -rf debian
    git clone -b 1.3 --depth=1 "$REPO_BASE/$r.git" debian
    rm -rf debian/.git
    echo '3.0 (native)' > debian/source/format
    [ "$r" != xapian-bindings ] || echo php > debian/bindings-to-package
    git add --all debian
    git difftool --cached debian
    cd "$here"
done
