#!/usr/bin/perl
use strict;
use warnings;
my $copyright = <<'EOF';
/* Copyright (C) 2012,2013 Olly Betts
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
EOF

use Tokeniseise;

my $srcdir = shift @ARGV;

my $hdr = Tokeniseise->new('my-html-tok.h', 'Map string to html tag code', $copyright, 'XAPIAN_INCLUDED_MY_HTML_TOK_H', 'html_tag');
my @space = ();
$hdr->append('enum { SPACE = 1, COLUMN = 2, BREAK = 3, BLOCK = 4, NOCLOSE = 8, TOKEN_SPACE_MASK = 7 };');
$hdr->append('');
$hdr->append('static const unsigned char token_space[] = {');
while (<STDIN>) {
    my @f = split /\s+/;
    my $enum = uc $f[0];
    $hdr->add($f[0], $enum);
    my $space = 0;
    if (exists $f[1]) {
	$space = $f[1];
	if (exists $f[2]) {
	    if ($f[2] ne 'NOCLOSE') {
		die "Expected 'NOCLOSE', got '$f[2]'";
	    }
	    $space .= ' | NOCLOSE';
	}
    }
    $hdr->append("    $space,");
}
$hdr->append('};');

$hdr->write();
