#!/usr/bin/perl -w
use strict;

my ($srcdir, $version) = @ARGV;

open Q, "$srcdir/query.cc" or die $!;
my @noparam = ();
my @param = ();
while (<Q>) {
    next unless /^T\((\w+),\s*(\w+),\s*(\w+)/;
    push @noparam, $1 if $2 eq '0';
    push @param, $1 if $3 ne '0';
}
close Q;

my $noparam = join(' ', @noparam);
my $param = join(' ', @param);

open I, "$srcdir/extra/omegascript.vim.in" or die $!;
mkdir 0755, 'extra' unless $srcdir eq '.' || -d 'extra';
open O, '>', 'extra/omegascript.vim.tmp' or die $!;
while (<I>) {
    s/\@([A-Z_]+)\@/var($1)/eg;
    print O;
}
close O;
close I;
rename 'extra/omegascript.vim.tmp', 'extra/omegascript.vim';

sub var {
    my $v = shift;
    return $version if ($v eq 'VERSION');
    return $param if ($v eq 'OMEGASCRIPT_PARAM');
    return $noparam if ($v eq 'OMEGASCRIPT_NO_PARAM');
    die "Unknown replacement token \@$v\@\n";
}
