#!/usr/bin/perl -wpi
# Copyright (C) 2009 Olly Betts
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

# Run with a list of files to update, e.g. for the whole xapian-core tree:
# ./c++stdcheaders  */*{,/*}.{h,cc}

s/^(#\s*include <)(assert|ctype|errno|float|limits|math|setjmp|signal|stdarg|stddef|stdint|stdio|stdlib|string|time)\.h>/$1c$2>/
