#!/bin/sh

set -e

if test -z "$1" ; then
    echo "Syntax: $0 VERSION"
    echo "e.g. $0 0.8.1"
    exit 1
fi

# directories to cvs tag
released_dirs="xapian-core xapian-examples xapian-bindings xapian-applications/omega"

# get path to top of CVS repo
srcdir="`echo $0|sed 's![^/]*$!!;s!^xapian-maintainer-tools/$!!;s!^./$!../!;s!/xapian-maintainer-tools/$!/!'`"

# check all the directories we need are checked out
for dir in $released_dirs ; do
    if test -d "$srcdir$dir" ; then
        :
    else
	echo "\`$srcdir$dir' not a directory - you need a complete CVS checkout"
	exit 1
    fi
done

cvstag="v`echo "$1"|sed 's/\./-/g'`"

# cvs tag
for dir in $released_dirs ; do
    (cd "$srcdir$dir" && cvs tag "$cvstag")||exit $?
done
(cd "$srcdir" && cvs tag "$cvstag" bootstrap)||exit $?
