/* Warning: This file is generated by ./collate-test - do not modify directly! */
extern bool test_check_db_path();
extern bool test_check_train_model();
extern bool test_listnet_ranker();
extern bool test_svm_ranker();
extern bool test_createfeaturevector();
