// cvsindex.C
//
// (c) 2001 Amir Michail (amir@users.sourceforge.net)

// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.

//
// Usage:  cvsindex package1.db package2.db ...
//
//                     => processes package.db and package.offset generated by cvsmap
//                     => builds a directory 'package' with quartz database inside
//
//  Warning:  it always deletes the directory package if it exists already.

#include <om/om.h>
#include <db_cxx.h>
#include <fstream.h>
#include <stdio.h>

#include "util.h"

#define FLUSH_RATE 50


int main(int argc, char *argv[]) {

  if(argc < 2) {
    cout << "Usage:  " << argv[0] <<
      " <path to database>" << endl;
    exit(1);
  }

  for (int i = 1; i < argc; i++ ) {

    string package = argv[i];

    int p = package.find(".db");
    if ( p == -1 ) {
      cerr << "Must include .db extension in package(s)." << endl;
      exit(1);
    }

    package = string(package, 0, p);

    cerr << "package -" << package << "-" << endl;

    // remove directory first if it already exists

    assert( package != "." ); // safety checks
    assert( package != ".." );

    cerr << "... removing directory " << package << " (if it already exists)" << endl;
    system( ("rm -rf " + package).c_str() );

    string file_db = package + ".db";
    string file_offset = package +".offset";

    try {


 
      // create database directory
      system(("mkdir " + package).c_str());

      // code which accesses Omsee

      OmSettings db_parameters;
      db_parameters.set("backend", "quartz");
      db_parameters.set("quartz_dir", package);
      OmWritableDatabase database(db_parameters); // open database 

      database.begin_session();

      // also write out file:line -> comments mapping using sleepy cat
      //      Db db(0, 0);
      //      db.open((package+"/comments.db").c_str(), 0, DB_HASH, DB_CREATE, 0 );


      ////////////////////////////////// cycle through each document

      cerr << "... reading " << file_db << endl;

      int files = 0;
      Lines lines( "", file_db, file_offset, false ); // no stop words
      string prev_file = "";
      while ( lines.ReadNextLine() ) {
	if ( lines.currentFile() != prev_file ) {
	  prev_file = lines.currentFile();
	  files++;
	  if ( files % FLUSH_RATE == 0 ) {
	    cerr << "** FLUSHING" << endl;
	    database.flush();
	  }
	}
	

	list<string> words = lines.getTermList();
	string data = lines.getData();
	// we want to output something like:
	// 0.453 80 15:1.8 1.3 1.1
	// 0.453 is the score
	// 80 is the file number
	// 15 is the line number

	// so, along with each entry, we store the following associated string:
	// 80 15:1.8 1.3 1.1
	

	OmDocumentContents newdocument;
	int pos = 1;
	for( list<string>::iterator i = words.begin(); i != words.end(); i++ ) {
	  
	  string word = *i;
	  newdocument.add_posting(word, pos++); // term, position of term
	}
	newdocument.data = data;
	database.add_document(newdocument);

      }
      


      //      db.close(0);
      database.end_session();

      cerr << "Done!" << endl;

    }
    catch(OmError & error) {
      cerr << "OMSEE Exception: " << error.get_msg() << endl;
    } 
    catch (DbException& e ) {
      cerr << "SleepyCat Exception: " << e.what() << endl;
    }

  }
  
}
