#!/usr/bin/perl -w
# Copyright (C) 2004,2005 Olly Betts
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA

use strict;

grep {$_ eq '--help'} @ARGV and die "Syntax: $0 [MBOX...]\n";

my $hdr = 1;
line: while (<>) {
    if ($hdr) {
	chomp;
	while (1) {
	    if (/^$/) {
		print "body=\n";
		$hdr = 0;
		next line;
	    }
	    # Handle continuation lines
	    my $line = $_;
	    while (<>) {
		chomp;
		last unless /^[ \t]/;
		$line .= $_;
	    }
	    if ($line =~ s/^Message-ID:\s*<?(.*?)>?\s*$/$1/i) {
		print "id=$line\n" if length $line;
	    } elsif ($line =~ s/^Subject:\s*(.*?)\s*$/$1/i) {
		print "title=$line\n" if length $line;
	    }
	}
    }

    if (/^From /) {
	print "\n";
	$hdr = 1;
	next;
    }
    if ($_ !~ /^\s+$/) {
	print "=$_";
    }
}
