/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_muscat_om_OmExpandOptions */

#ifndef _Included_com_muscat_om_OmExpandOptions
#define _Included_com_muscat_om_OmExpandOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_muscat_om_OmExpandOptions
 * Method:    createNativeObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_muscat_om_OmExpandOptions_createNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     com_muscat_om_OmExpandOptions
 * Method:    deleteNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_muscat_om_OmExpandOptions_deleteNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     com_muscat_om_OmExpandOptions
 * Method:    use_query_terms
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_muscat_om_OmExpandOptions_use_1query_1terms
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
