/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webtop_om_OmMSet */

#ifndef _Included_com_webtop_om_OmMSet
#define _Included_com_webtop_om_OmMSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_webtop_om_OmMSet
 * Method:    deleteNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_webtop_om_OmMSet_deleteNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     com_webtop_om_OmMSet
 * Method:    get_firstitem
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_webtop_om_OmMSet_get_1firstitem
  (JNIEnv *, jobject);

/*
 * Class:     com_webtop_om_OmMSet
 * Method:    get_items
 * Signature: ()Lcom/webtop/om/OmVector;
 */
JNIEXPORT jobject JNICALL Java_com_webtop_om_OmMSet_get_1items
  (JNIEnv *, jobject);

/*
 * Class:     com_webtop_om_OmMSet
 * Method:    get_max_attained
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_webtop_om_OmMSet_get_1max_1attained
  (JNIEnv *, jobject);

/*
 * Class:     com_webtop_om_OmMSet
 * Method:    get_max_possible
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_webtop_om_OmMSet_get_1max_1possible
  (JNIEnv *, jobject);

/*
 * Class:     com_webtop_om_OmMSet
 * Method:    get_mbound
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_webtop_om_OmMSet_get_1mbound
  (JNIEnv *, jobject);

/*
 * Class:     com_webtop_om_OmMSet
 * Method:    convert_to_percent
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_com_webtop_om_OmMSet_convert_1to_1percent
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
