/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webtop_om_OmDocument */

#ifndef _Included_com_webtop_om_OmDocument
#define _Included_com_webtop_om_OmDocument
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_webtop_om_OmDocument
 * Method:    deleteNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_webtop_om_OmDocument_deleteNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     com_webtop_om_OmDocument
 * Method:    get_key
 * Signature: (I)Lcom/webtop/om/OmKey;
 */
JNIEXPORT jobject JNICALL Java_com_webtop_om_OmDocument_get_1key
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_webtop_om_OmDocument
 * Method:    get_data
 * Signature: ()Lcom/webtop/om/OmData;
 */
JNIEXPORT jobject JNICALL Java_com_webtop_om_OmDocument_get_1data
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
