/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_muscat_om_OmMSetItem */

#ifndef _Included_com_muscat_om_OmMSetItem
#define _Included_com_muscat_om_OmMSetItem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_muscat_om_OmMSetItem
 * Method:    deleteNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_muscat_om_OmMSetItem_deleteNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     com_muscat_om_OmMSetItem
 * Method:    get_did
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_muscat_om_OmMSetItem_get_1did
  (JNIEnv *, jobject);

/*
 * Class:     com_muscat_om_OmMSetItem
 * Method:    get_wt
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_muscat_om_OmMSetItem_get_1wt
  (JNIEnv *, jobject);

/*
 * Class:     com_muscat_om_OmMSetItem
 * Method:    get_collapse_key
 * Signature: ()Lcom/muscat/om/OmKey;
 */
JNIEXPORT jobject JNICALL Java_com_muscat_om_OmMSetItem_get_1collapse_1key
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
