/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webtop_om_OmPrefixExpandDecider */

#ifndef _Included_com_webtop_om_OmPrefixExpandDecider
#define _Included_com_webtop_om_OmPrefixExpandDecider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_webtop_om_OmPrefixExpandDecider
 * Method:    createNativeObject
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_webtop_om_OmPrefixExpandDecider_createNativeObject
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_webtop_om_OmPrefixExpandDecider
 * Method:    deleteNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_webtop_om_OmPrefixExpandDecider_deleteNativeObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
