/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webtop_om_OmMSetItemVector */

#ifndef _Included_com_webtop_om_OmMSetItemVector
#define _Included_com_webtop_om_OmMSetItemVector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_webtop_om_OmMSetItemVector
 * Method:    deleteNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_webtop_om_OmMSetItemVector_deleteNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     com_webtop_om_OmMSetItemVector
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_webtop_om_OmMSetItemVector_size
  (JNIEnv *, jobject);

/*
 * Class:     com_webtop_om_OmMSetItemVector
 * Method:    elementAt
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_webtop_om_OmMSetItemVector_elementAt
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
