/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webtop_om_OmQuery */

#ifndef _Included_com_webtop_om_OmQuery
#define _Included_com_webtop_om_OmQuery
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_webtop_om_OmQuery
 * Method:    deleteNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_webtop_om_OmQuery_deleteNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     com_webtop_om_OmQuery
 * Method:    createNativeObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_webtop_om_OmQuery_createNativeObject__
  (JNIEnv *, jobject);

/*
 * Class:     com_webtop_om_OmQuery
 * Method:    createNativeObject
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_com_webtop_om_OmQuery_createNativeObject__Ljava_lang_String_2II
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_webtop_om_OmQuery
 * Method:    createNativeObject
 * Signature: (Ljava/lang/String;Lcom/webtop/om/OmQuery;Lcom/webtop/om/OmQuery;)J
 */
JNIEXPORT jlong JNICALL Java_com_webtop_om_OmQuery_createNativeObject__Ljava_lang_String_2Lcom_webtop_om_OmQuery_2Lcom_webtop_om_OmQuery_2
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     com_webtop_om_OmQuery
 * Method:    createNativeObject
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_webtop_om_OmQuery_createNativeObject__Ljava_lang_String_2_3Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     com_webtop_om_OmQuery
 * Method:    get_terms
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_webtop_om_OmQuery_get_1terms
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
