/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webtop_om_OmESetItem */

#ifndef _Included_com_webtop_om_OmESetItem
#define _Included_com_webtop_om_OmESetItem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_webtop_om_OmESetItem
 * Method:    deleteNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_webtop_om_OmESetItem_deleteNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     com_webtop_om_OmESetItem
 * Method:    get_tname
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_webtop_om_OmESetItem_get_1tname
  (JNIEnv *, jobject);

/*
 * Class:     com_webtop_om_OmESetItem
 * Method:    get_wt
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_webtop_om_OmESetItem_get_1wt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
