/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webtop_om_OmExpandDecider */

#ifndef _Included_com_webtop_om_OmExpandDecider
#define _Included_com_webtop_om_OmExpandDecider
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
