/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webtop_om_OmESet */

#ifndef _Included_com_webtop_om_OmESet
#define _Included_com_webtop_om_OmESet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_webtop_om_OmESet
 * Method:    deleteNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_webtop_om_OmESet_deleteNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     com_webtop_om_OmESet
 * Method:    get_items
 * Signature: ()Lcom/webtop/om/OmVector;
 */
JNIEXPORT jobject JNICALL Java_com_webtop_om_OmESet_get_1items
  (JNIEnv *, jobject);

/*
 * Class:     com_webtop_om_OmESet
 * Method:    get_ebound
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_webtop_om_OmESet_get_1ebound
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
