/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_muscat_om_OmEnquire */

#ifndef _Included_com_muscat_om_OmEnquire
#define _Included_com_muscat_om_OmEnquire
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_muscat_om_OmEnquire
 * Method:    createNativeObject
 * Signature: (Lcom/muscat/om/OmDatabaseGroup;)J
 */
JNIEXPORT jlong JNICALL Java_com_muscat_om_OmEnquire_createNativeObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_muscat_om_OmEnquire
 * Method:    deleteNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_muscat_om_OmEnquire_deleteNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     com_muscat_om_OmEnquire
 * Method:    get_doc
 * Signature: (Lcom/muscat/om/OmMSetItem;)Lcom/muscat/om/OmDocument;
 */
JNIEXPORT jobject JNICALL Java_com_muscat_om_OmEnquire_get_1doc__Lcom_muscat_om_OmMSetItem_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_muscat_om_OmEnquire
 * Method:    get_doc
 * Signature: (I)Lcom/muscat/om/OmDocument;
 */
JNIEXPORT jobject JNICALL Java_com_muscat_om_OmEnquire_get_1doc__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_muscat_om_OmEnquire
 * Method:    get_mset
 * Signature: (IILcom/muscat/om/OmRSet;Lcom/muscat/om/OmMatchOptions;Lcom/muscat/om/OmMatchDecider;)Lcom/muscat/om/OmMSet;
 */
JNIEXPORT jobject JNICALL Java_com_muscat_om_OmEnquire_get_1mset
  (JNIEnv *, jobject, jint, jint, jobject, jobject, jobject);

/*
 * Class:     com_muscat_om_OmEnquire
 * Method:    set_query
 * Signature: (Lcom/muscat/om/OmQuery;)V
 */
JNIEXPORT void JNICALL Java_com_muscat_om_OmEnquire_set_1query
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_muscat_om_OmEnquire
 * Method:    get_eset
 * Signature: (ILcom/muscat/om/OmRSet;Lcom/muscat/om/OmExpandOptions;Lcom/muscat/om/OmExpandDecider;)Lcom/muscat/om/OmESet;
 */
JNIEXPORT jobject JNICALL Java_com_muscat_om_OmEnquire_get_1eset
  (JNIEnv *, jobject, jint, jobject, jobject, jobject);

/*
 * Class:     com_muscat_om_OmEnquire
 * Method:    get_matching_terms
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_muscat_om_OmEnquire_get_1matching_1terms
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
