/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_muscat_om_OmMatchOptions */

#ifndef _Included_com_muscat_om_OmMatchOptions
#define _Included_com_muscat_om_OmMatchOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_muscat_om_OmMatchOptions
 * Method:    createNativeObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_muscat_om_OmMatchOptions_createNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     com_muscat_om_OmMatchOptions
 * Method:    deleteNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_muscat_om_OmMatchOptions_deleteNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     com_muscat_om_OmMatchOptions
 * Method:    set_collapse_key
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_muscat_om_OmMatchOptions_set_1collapse_1key
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_muscat_om_OmMatchOptions
 * Method:    set_no_collapse
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_muscat_om_OmMatchOptions_set_1no_1collapse
  (JNIEnv *, jobject);

/*
 * Class:     com_muscat_om_OmMatchOptions
 * Method:    set_sort_forward
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_muscat_om_OmMatchOptions_set_1sort_1forward
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_muscat_om_OmMatchOptions
 * Method:    set_percentage_cutoff
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_muscat_om_OmMatchOptions_set_1percentage_1cutoff
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_muscat_om_OmMatchOptions
 * Method:    set_max_or_terms
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_muscat_om_OmMatchOptions_set_1max_1or_1terms
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
