/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_muscat_om_OmESetItemVector */

#ifndef _Included_com_muscat_om_OmESetItemVector
#define _Included_com_muscat_om_OmESetItemVector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_muscat_om_OmESetItemVector
 * Method:    deleteNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_muscat_om_OmESetItemVector_deleteNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     com_muscat_om_OmESetItemVector
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_muscat_om_OmESetItemVector_size
  (JNIEnv *, jobject);

/*
 * Class:     com_muscat_om_OmESetItemVector
 * Method:    elementAt
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_muscat_om_OmESetItemVector_elementAt
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
