/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_muscat_om_OmDatabaseGroup */

#ifndef _Included_com_muscat_om_OmDatabaseGroup
#define _Included_com_muscat_om_OmDatabaseGroup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_muscat_om_OmDatabaseGroup
 * Method:    createNativeObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_muscat_om_OmDatabaseGroup_createNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     com_muscat_om_OmDatabaseGroup
 * Method:    deleteNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_muscat_om_OmDatabaseGroup_deleteNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     com_muscat_om_OmDatabaseGroup
 * Method:    add_database
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_muscat_om_OmDatabaseGroup_add_1database
  (JNIEnv *, jobject, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
