/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webtop_om_OmRSet */

#ifndef _Included_com_webtop_om_OmRSet
#define _Included_com_webtop_om_OmRSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_webtop_om_OmRSet
 * Method:    createNativeObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_webtop_om_OmRSet_createNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     com_webtop_om_OmRSet
 * Method:    deleteNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_webtop_om_OmRSet_deleteNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     com_webtop_om_OmRSet
 * Method:    get_items
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_webtop_om_OmRSet_get_1items
  (JNIEnv *, jobject);

/*
 * Class:     com_webtop_om_OmRSet
 * Method:    add_document
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_webtop_om_OmRSet_add_1document
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_webtop_om_OmRSet
 * Method:    remove_document
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_webtop_om_OmRSet_remove_1document
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
