#!/usr/bin/perl
# Copyright (c) 2016,2019 Olly Betts
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

use strict;
use warnings;

undef $/;
$_ = <>;

my ($pos, $find, $replace);

# Reject Python 2 (there are separate bindings for Python 2).
s/^(if _swig_python_version_info < )\(2, 7, 0\)(:\n    raise.*?) 2\.7 or later\b/$1(3, 0, 0)$2 3/m or
    die "Failed to fix up version check";

s/^try:\n    import builtins as __builtin__.*?\n    import __builtin__\n//sm or
    die "Failed to fix up import code";

$replace = << '__END__';
def _swig_repr(self):
    strthis = ""
    if hasattr(self.this, '__repr__'):
        strthis = "proxy of " + self.this.__repr__()
__END__
s/^(?:def _swig_setattr_nondynamic\(self.*?\n)?def _swig_repr\(self\):.*?(\n    return)/$replace$1/sm or
    die "Failed to fix up _swig_repr";

s/^def _swig_setattr_nondynamic.*?\nclass _SwigNonDynamicMeta\(type\):.*?\n\n//sm or
    die "Failed to fix up _swig_setattr_nondynamic";

/\b__builtin__\b/ and
    die "Failed to fully fix up __builtin__";

/\b_swig_[gs]etattr/ and
    die "Failed to fully fix up _swig_getattr/_swig_setattr*";

print;

# Workaround Perl 5.28 -i quirk:
<>;
