[build-system]
requires = ["setuptools ==  80.9.0"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "xapian"
description = "Xapian bindigs for Python"
requires-python = ">= 3"
dependencies = []
license = "GPL-2.0-or-later"
authors = []
classifiers = []

[project.urls]
Homepage = 'https://xapian.org/'

[tool.setuptools]
packages = { find = { include = ["xapian"] } }
