#!/usr/bin/perl
use strict;
use warnings;

# If App::Prove isn't found, exit with status 77 which causes the testharness
# to treat the tests as skipped.
#
# App::Prove is a Perl core module so it's unlikely to be missing, but e.g. on
# Debian you might be able to have perl-core installed with perl.
eval { require App::Prove };
$@ and exit 77;

my $app = App::Prove->new;
unshift @ARGV, "-I$ENV{srcdir}" if exists $ENV{srcdir};
unshift @ARGV, '-I.';
$app->process_args(@ARGV);
exit($app->run ? 0 : 1);
