#! /bin/sh
test -n "$srcdir" && cd $srcdir
echo "dnl  acinclude.m4" >acinclude.m4
echo "dnl  This file is automatically generated, by genacinclude.sh." >>acinclude.m4
echo "dnl  DO NOT EDIT THIS FILE." >>acinclude.m4
for a in $* ; do
    echo "" >>acinclude.m4
    echo "dnl  Including file $a:" >>acinclude.m4
    cat autoconf/$a >>acinclude.m4
done
