#! /bin/sh
m4_files="cme_find_socketpair.m4 rjb_find_gethostent.m4 \
	     rjb_find_stlport.m4 rjb_check_berkeleydb.m4"

test -n "$srcdir" && cd $srcdir
echo "dnl  acinclude.m4" >acinclude.m4
echo "dnl  This file is automatically generated, by genacinclude.sh." >>acinclude.m4
echo "dnl  DO NOT EDIT THIS FILE." >>acinclude.m4
for a in $m4_files ; do
    echo "" >>acinclude.m4
    echo "dnl  Including file $a:" >>acinclude.m4
    cat autoconf/$a >>acinclude.m4
done
