#!/usr/bin/perl
#
# Copyright (C) 2013,2014 Olly Betts
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

use strict;
use warnings;

my @fd = qw(STDIN STDOUT STDERR);
while (<>) {
    if (/^pread(?:64)?\((\d+).*, (\d+), (\d+)\)/) {
        my ($fd, $blocksize, $off) = ($1, $2, $3);
        my $block = $off / $blocksize;
        print "read $block from $fd[$fd]\n";
    } elsif (/^open\("(.*)".* = (\d+)/) {
	$fd[$2] = $1;
    } elsif (/^close\((\d+)/) {
        $fd[$1] = undef;
    } elsif (/^dup[23]?\((\d+).* = (\d+)/) {
        $fd[$2] = $fd[$1];
    }
}
