#!/bin/sh -x
# Make Debian source packages from a xapian source tree.
#
# Copyright (C) 2004 Richard Boulton
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA

set -e

# CVS tag to use to check out Xapian sources
# If this is of the form "vMAJOR-MINOR-PATCH", where MAJOR, MINOR and PATCH
# are integers, we are building a release, and will build from a tarball
# (which we will generate from CVS code if the tarball isn't already
# cached in our target directory.)
# Otherwise, we are building a snapshot package, and will build directly
# from CVS code.  (FIXME - currently generates from a cached tarball if there
# is one.  Not sure this is a bad thing.)
CVSTAG='v0-8-2'

# CVS tags to use to check out Debian control files
DEBTAG_CORE='debian0-8-2_3'
DEBTAG_BINDINGS='debian0-8-2_2'
DEBTAG_OMEGA='debian0-8-2_2'

#CVSTAG=HEAD
#DEBTAG_CORE=HEAD
#DEBTAG_BINDINGS=HEAD
#DEBTAG_OMEGA=HEAD

# Debian component to build for (libc version being the most important factor)
COMPONENT=stable

# Options to pass to dpkg-buildpackage when building source packages
BUILDPACKAGE_SRC_OPTS="-us -uc -d -S"
# Options to pass to dpkg-buildpackage when building binary packages
BUILDPACKAGE_BIN_OPTS="-us -uc -d -b"

# Location to place the generated apt repository
PUBDIR="/usr/data/www/xapian.org/debian"


## Items after this point should not normally need to be modified

# Location to download tarballs from.
CVSROOT=":pserver:cvsuser@cvs.xapian.org:/usr/data/cvs"


## BEGIN PROCESSING ##
trap "echo \"makedebs failed\"" EXIT

# Determine the architecture we're building on
DEB_HOST_ARCH=`dpkg-architecture -qDEB_HOST_ARCH`

# Detect if we're on the machine that Xapian CVS is held on, and don't use
# pserver to check out sources if so.
if [ "x`hostname`" == "xixion" ] ; then
  if [ -r '/usr/data/cvs/xapian' ] ; then
    CVSROOT="/usr/data/cvs"
  fi
fi

# Calculate the version which we're building.
# $VERSION holds the version number as defined in configure.in.
# $EXTRA_VERSION_UPSTREAM holds a suffix to be added to the upstream
# version number (empty when building a release)
# $EXTRA_VERSION_DEBIAN holds a suffix to be added to the debian
# version number (empty when building for the current distribution)
# Finally, $SNAP_VERSION will be set to "$VERSION$EXTRA_VERSION_UPSTREAM"
# (and will therefore be identical to $VERSION when building a release).

VERSION="`echo ${CVSTAG} | sed 's/^v\([0-9][0-9]*\)-\([0-9][0-9]*\)-\([0-9][0-9]*\)$/\1.\2.\3/g'`"
EXTRA_VERSION_UPSTREAM=""
EXTRA_VERSION_DEBIAN=""

# If we are building a version other than that specified in the
# debian control file, we need to make an entry in the debian changelog.
# $CHANGE_MSG holds the message to put in the entry.
CHANGE_MSG=""

# If we failed to parse the tag into a version number, we are not building
# a tagged release.  We will therefore have to get the version number from
# the source code.
if [ "x$VERSION" == "x$CVSTAG" ] ; then
  VERSION="`cvs -Q -d ${CVSROOT} co -r $CVSTAG -p xapian/xapian-core/configure.in | grep AC_INIT | head -n 1 | sed 's/^.*xapian-core, \([0-9][0-9]*\)\.\([0-9][0-9]*\)\.\([0-9][0-9]*\)[^0-9].*$/\1.\2.\3/g'`"
  # For now, append the current date to snapshot builds.
  # FIXME - should use the date of last modification to the snapshot.
  EXTRA_VERSION_UPSTREAM=".`date '+%Y%m%d'`"
  CHANGE_MSG="  * Snapshot build.
"
fi

# If we're building for the stable distribution, we need to add a bit
# to the debian version number, to avoid conflicts with the package in
# unstable.  We add "0stable" since it should sort before any other
# modification.
if [ "x$COMPONENT" == "xstable" ] ; then
  EXTRA_VERSION_DEBIAN=".0stable"
  CHANGE_MSG="$CHANGE_MSG  * Built for stable distribution.
"
fi

SNAP_VERSION="$VERSION$EXTRA_VERSION_UPSTREAM"

# Finish the contents of the changelog entry, if one is to be made.
if [ "x$CHANGE_MSG" != "x" ] ; then
  CHANGE_MSG="
$CHANGE_MSG
 -- Richard Boulton <richard@tartarus.org>  `822-date`
"
fi

# Checkout debian control files from CVS
mkdir -p control
cd control
  cvs -Q -d ${CVSROOT} co -r ${DEBTAG_CORE} -d xapian-core xapian/xapian-core/debian
  cvs -Q -d ${CVSROOT} co -r ${DEBTAG_BINDINGS} -d xapian-bindings xapian/xapian-bindings/debian
  cvs -Q -d ${CVSROOT} co -r ${DEBTAG_OMEGA} -d xapian-omega xapian/xapian-applications/omega/debian
cd ..

# TARGETDIR is the location that all generated files will be stored in.
if [ "x$EXTRA_VERSION_UPSTREAM" == "x" ] ; then
  TARGETDIR="dists/$COMPONENT/main"
else
  TARGETDIR="dists/$COMPONENT/snapshot"
fi
SRCDIR="$TARGETDIR/source"
POOLDIR="pool/$VERSION"
mkdir -p "$PUBDIR/$SRCDIR"

# Calculate location that tarballs should be found at
TARBALL_CORE="${PUBDIR}/$POOLDIR/source/xapian-core_${SNAP_VERSION}.orig.tar.gz"
TARBALL_BINDINGS="${PUBDIR}/$POOLDIR/source/xapian-bindings_${SNAP_VERSION}.orig.tar.gz"
TARBALL_OMEGA="${PUBDIR}/$POOLDIR/source/xapian-omega_${SNAP_VERSION}.orig.tar.gz"

# Make tarballs, if we don't already have some
if [ -e ${TARBALL_CORE} -a -e ${TARBALL_BINDINGS} -a -e ${TARBALL_OMEGA} ];
then
  # Distribution tarballs all exist
  true
else
  # Checkout original packages from CVS
  rm -rf origsrc
  mkdir -p origsrc
  cd origsrc
    cvs -Q -d ${CVSROOT} co -r $CVSTAG xapian
    cd xapian
      ./bootstrap
      ./configure --enable-maintainer-mode
      if [ -e ${TARBALL_CORE} ]; then true; else
        cd xapian-core
	  make dist
	  if [ $VERSION != $SNAP_VERSION ] ; then
	    rm -rf distdir
	    mkdir -p distdir
	    tar zxf xapian-core-${VERSION}.tar.gz
	    mv xapian-core-${VERSION} xapian-core-${SNAP_VERSION}
	    tar zcf xapian-core-${SNAP_VERSION}.tar.gz xapian-core-${SNAP_VERSION}
	  fi
	  cp xapian-core-${SNAP_VERSION}.tar.gz ${TARBALL_CORE}
	cd ..
      fi
      if [ -e ${TARBALL_BINDINGS} ]; then true; else
        cd xapian-bindings
	  # We have to invoke automake here because otherwise what looks like
	  # a bug in autoreconf causes the generated Makefile.in to miss
	  # depcomp from the list of files to include in distributions.
	  # Running automake explicitly works around the problem.
	  automake
	  make dist
	  if [ $VERSION != $SNAP_VERSION ] ; then
	    rm -rf distdir
	    mkdir -p distdir
	    tar zxf xapian-bindings-${VERSION}.tar.gz
	    mv xapian-bindings-${VERSION} xapian-bindings-${SNAP_VERSION}
	    tar zcf xapian-bindings-${SNAP_VERSION}.tar.gz xapian-bindings-${SNAP_VERSION}
	  fi
	  cp xapian-bindings-${SNAP_VERSION}.tar.gz ${TARBALL_BINDINGS}
	cd ..
      fi
      if [ -e ${TARBALL_OMEGA} ]; then true; else
        cd xapian-applications/omega
	  make dist
	  rm -rf distdir
	  mkdir -p distdir
	  tar zxf omega-${VERSION}.tar.gz
	  mv omega-${VERSION} xapian-omega-${SNAP_VERSION}
	  tar zcf xapian-omega-${SNAP_VERSION}.tar.gz xapian-omega-${SNAP_VERSION}
	  cp xapian-omega-${SNAP_VERSION}.tar.gz ${TARBALL_OMEGA}
	cd ../..
      fi
    cd ..
  cd ..
  rm -rf origsrc
fi

# Unpack distribution tarballs, and put the debian control files into place,
# and build source packages
rm -rf build
mkdir -p build
cd build
  # Build packages from xapian-core
  cp -a ${TARBALL_CORE} .
  tar zxf ${TARBALL_CORE}
  cd xapian-core-${SNAP_VERSION}
    mkdir -p debian
    cp -af ../../control/xapian-core/* debian/
    rm -rf debian/CVS
    if [ "x$CHANGE_MSG" != "x" ] ; then
      head -n 1 debian/changelog | sed "s/(\([^-]*\)\(.*\)).*$/(\1$EXTRA_VERSION_UPSTREAM\2$EXTRA_VERSION_DEBIAN) unstable; urgency=low/" > debian/changelog.new
      echo "$CHANGE_MSG" >> debian/changelog.new
      cat debian/changelog >> debian/changelog.new
      mv debian/changelog.new debian/changelog
    fi

    debian/rules # Generates generate control from control.in
    fakeroot dpkg-buildpackage ${BUILDPACKAGE_SRC_OPTS}
  cd ..

  # Build packages from xapian-bindings
  cp -a ${TARBALL_BINDINGS} .
  tar zxf ${TARBALL_BINDINGS}
  cd xapian-bindings-${SNAP_VERSION}
    mkdir -p debian
    cp -af ../../control/xapian-bindings/* debian/
    rm -rf debian/CVS
    if [ "x$CHANGE_MSG" != "x" ] ; then
      head -n 1 debian/changelog | sed "s/(\([^-]*\)\(.*\)).*$/(\1$EXTRA_VERSION_UPSTREAM\2$EXTRA_VERSION_DEBIAN) unstable; urgency=low/" > debian/changelog.new
      echo "$CHANGE_MSG" >> debian/changelog.new
      cat debian/changelog >> debian/changelog.new
      mv debian/changelog.new debian/changelog
    fi
    if [ -r debian/patch ]; then
      patch -p0 <debian/patch
    fi
    echo "$COMPONENT" >debian/component
    debian/rules # Generates control from control.in and control-python.in
    fakeroot dpkg-buildpackage ${BUILDPACKAGE_SRC_OPTS}
  cd ..

  # Build packages from xapian-omega
  cp -a ${TARBALL_OMEGA} .
  tar zxf ${TARBALL_OMEGA}
  cd xapian-omega-${SNAP_VERSION}
    mkdir -p debian
    cp -af ../../control/xapian-omega/* debian/
    rm -rf debian/CVS
    if [ "x$CHANGE_MSG" != "x" ] ; then
      head -n 1 debian/changelog | sed "s/(\([^-]*\)\(.*\)).*$/(\1$EXTRA_VERSION_UPSTREAM\2$EXTRA_VERSION_DEBIAN) unstable; urgency=low/" > debian/changelog.new
      echo "$CHANGE_MSG" >> debian/changelog.new
      cat debian/changelog >> debian/changelog.new
      mv debian/changelog.new debian/changelog
    fi
    fakeroot dpkg-buildpackage ${BUILDPACKAGE_SRC_OPTS}
  cd ..

# FIXME - Build packages from xapian-examples

# Leave the build directory
cd ..

# Create source package repository
src_files="build/xapian*.dsc build/xapian*.diff.gz build/xapian*.changes build/xapian*.tar.gz"
rm -rf "upload-sources"
mkdir -p "upload-sources/$SRCDIR"
mkdir -p "upload-sources/$POOLDIR/source"
mkdir -p "upload-sources/$POOLDIR/binary"
mv $src_files upload-sources/$POOLDIR/source
cat >upload-sources/$SRCDIR/Release <<EOF
Archive: $COMPONENT
Component: main
Origin: Xapian
Label: Xapian
Architecture: source
EOF
cd upload-sources
  dpkg-scansources . /dev/null | gzip -9 > $SRCDIR/Sources.gz
cd ..

# Upload to $PUBDIR
mkdir -p ${PUBDIR}
chgrp -R xapian upload-sources/*
chmod -R g+w upload-sources/*
cp -af upload-sources/* ${PUBDIR}
chgrp -R xapian ${PUBDIR}/*
chmod -R g+w ${PUBDIR}/*

# Source packages are now generated and uploaded.

trap EXIT
echo "Made Debian source packages for $COMPONENT successfully"
