/* Warning: This file is generated by ./collate-test - do not modify directly! */
extern bool test_latlongparse1();
extern bool test_latlongparse2();
extern bool test_latlongparse3();
extern bool test_latlongpostingsource1();
