/** @file allsnowballheaders.h
 *  @brief Include the headers for all the snowball stemmers.
 */
/* Warning: This file is generated by languages/generate-allsnowballheaders - do not modify directly! */
/* Copyright (C) 2007 Olly Betts
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
 */

#ifndef XAPIAN_INCLUDED_ALLSNOWBALLHEADERS_H
#define XAPIAN_INCLUDED_ALLSNOWBALLHEADERS_H

#include "languages/danish.h"
#include "languages/dutch.h"
#include "languages/english.h"
#include "languages/finnish.h"
#include "languages/french.h"
#include "languages/german.h"
#include "languages/german2.h"
#include "languages/hungarian.h"
#include "languages/italian.h"
#include "languages/kraaij_pohlmann.h"
#include "languages/lovins.h"
#include "languages/norwegian.h"
#include "languages/porter.h"
#include "languages/portuguese.h"
#include "languages/romanian.h"
#include "languages/russian.h"
#include "languages/spanish.h"
#include "languages/swedish.h"
#include "languages/turkish.h"

#define LANGSTRING "danish dutch english finnish french german german2 hungarian italian kraaij_pohlmann lovins norwegian porter portuguese romanian russian spanish swedish turkish"

#endif // XAPIAN_INCLUDED_ALLSNOWBALLHEADERS_H
