case 173: ch = '-'; break;
case 192: ch = 'A'; break;
case 193: ch = 'A'; break;
case 194: ch = 'A'; break;
case 195: ch = 'A'; break;
case 196: ch = 'A'; cache = 'E'; break;
case 197: ch = 'A'; cache = 'A'; break;
case 198: ch = 'A'; cache = 'E'; break;
case 199: ch = 'C'; break;
case 200: ch = 'E'; break;
case 201: ch = 'E'; break;
case 202: ch = 'E'; break;
case 203: ch = 'E'; break;
case 204: ch = 'I'; break;
case 205: ch = 'I'; break;
case 206: ch = 'I'; break;
case 207: ch = 'I'; break;
case 208: ch = 'T'; cache = 'H'; break;
case 209: ch = 'N'; break;
case 210: ch = 'O'; break;
case 211: ch = 'O'; break;
case 212: ch = 'O'; break;
case 213: ch = 'O'; break;
case 214: ch = 'O'; cache = 'E'; break;
case 216: ch = 'O'; break;
case 217: ch = 'U'; break;
case 218: ch = 'U'; break;
case 219: ch = 'U'; break;
case 220: ch = 'U'; cache = 'E'; break;
case 221: ch = 'Y'; break;
case 222: ch = 'T'; cache = 'H'; break;
case 223: ch = 's'; cache = 's'; break;
case 224: ch = 'a'; break;
case 225: ch = 'a'; break;
case 226: ch = 'a'; break;
case 227: ch = 'a'; break;
case 228: ch = 'a'; cache = 'e'; break;
case 229: ch = 'a'; cache = 'a'; break;
case 230: ch = 'a'; cache = 'e'; break;
case 231: ch = 'c'; break;
case 232: ch = 'e'; break;
case 233: ch = 'e'; break;
case 234: ch = 'e'; break;
case 235: ch = 'e'; break;
case 236: ch = 'i'; break;
case 237: ch = 'i'; break;
case 238: ch = 'i'; break;
case 239: ch = 'i'; break;
case 240: ch = 't'; cache = 'h'; break;
case 241: ch = 'n'; break;
case 242: ch = 'o'; break;
case 243: ch = 'o'; break;
case 244: ch = 'o'; break;
case 245: ch = 'o'; break;
case 246: ch = 'o'; cache = 'e'; break;
case 248: ch = 'o'; break;
case 249: ch = 'u'; break;
case 250: ch = 'u'; break;
case 251: ch = 'u'; break;
case 252: ch = 'u'; cache = 'e'; break;
case 253: ch = 'y'; break;
case 254: ch = 't'; cache = 'h'; break;
case 255: ch = 'y'; break;
