#!/bin/sh
#
# genpage [-l] <infile> <type> [<inuri> [<xaproot>]]
#
# for website generation, type = docs or with-sidebar:
#
# XX.md docs
# XX.md with-sidebar
#
# for local docs generation, type = docs, docs-omega, docs-bindings etc
# which affects the local menu to use (menu-<type>-local.html)
#
# -l XX.md docs-omega

set -e

thisdir=`dirname $0`
xaproot=http://xapian.org/
stylesheet=style.css

frob_infile=0
if [ "x$1" = "x-l" ]; then
  infile=$2
  type=docs
  docsmenu=${thisdir}/menu-$3-local.html
  localflag=-b
  # really unpleasant hack, I apologise: silently, we know that
  # the bindings docs are two levels deep not one
  if [ "x$3" = "xdocs-bindings" ]; then
    outroot="../"
    stylesheet=../style.css
    localflag="-b -r ../"
  fi
  # another hack: we build omega docs with a default (calculated) <inuri>,
  # but this is calculated from the *full path* that make passes as <infile>
  # so we want to just grab the basename
  # (this has to be done later, so just set a flag for now)
  if [ "x$3" = "xdocs-omega" ]; then
    frob_infile=1
  fi
  shift
else
  outroot='REPLACE_WITH_XAPROOT'
  docsmenu=${thisdir}/menu-docs.html
  infile=$1
  type=$2
  localflag=
fi

if [ "x$3" != "x" ]; then
  inuri=$3
  if [ "x$4" != "x" ]; then
    xaproot=$4
  fi
else
  if [ "x$frob_infile" = "x1" ]; then
    inuri=`basename $infile`
  else
    inuri=$infile
  fi
fi

#if [ "x$4" != "x" ]; then
#  docsmenu=${thisdir}/$4.html
#fi

if [ "x$outroot" = "xREPLACE_WITH_XAPROOT" ]; then
  outroot=$xaproot
  stylesheet="$xaproot$stylesheet"
fi

PYTHON=/usr/bin/python

prebodytemplate=${thisdir}/templates/$type-PREBODY.html
postbodytemplate=${thisdir}/templates/$type-POSTBODY.html
headerextratemplate=${thisdir}/templates/header-extra.html

prebodytmp=`mktemp`
$PYTHON ${thisdir}/genhtml.py $prebodytemplate $infile inuri=$inuri outroot=$outroot xaproot=$xaproot thisdir=$thisdir docsmenu=$docsmenu localflag="$localflag" PYTHON=$PYTHON > $prebodytmp
postbodytmp=`mktemp`
$PYTHON ${thisdir}/genhtml.py $postbodytemplate $infile inuri=$inuri outroot=$outroot xaproot=$xaproot thisdir=$thisdir localflag="$localflag" PYTHON=$PYTHON > $postbodytmp
headerextratmp=`mktemp`
$PYTHON ${thisdir}/genhtml.py $headerextratemplate $infile inuri=$inuri outroot=$outroot xaproot=$xaproot thisdir=$thisdir localflag="$localflag" PYTHON=$PYTHON > $headerextratmp
if [ $type = "docs" ]; then
  pandoc --css=$stylesheet --toc --standalone --smart --include-before-body=$prebodytmp --include-after-body=$postbodytmp --include-in-header=$headerextratmp $infile
else
  pandoc --css=$stylesheet --standalone --smart --include-before-body=$prebodytmp --include-after-body=$postbodytmp --include-in-header=$headerextratmp $infile
fi
unlink $prebodytmp
unlink $postbodytmp
unlink $headerextratmp
