#!/bin/bash
# Create Debian-style package repository.
#
# Copyright (C) 2007 Olly Betts
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

set -e

if [ x"$1" = x--help -o "$#" -ne 1 ] ; then
  echo "Usage: $0 VERSION"
  echo "e.g. $0 1.0.1"
  exit 1
fi

VERSION=$1

# rsync the source packages down.
rsync -v -a ixion.tartarus.org:/usr/data/www/xapian.org/debian-tmp/ .
# We need Sources as well as Sources.gz.
for f in `find dists -name Sources.gz` ; do
  sources=`echo "$f"|sed 's/\.gz$//'`
  test -f "$sources" || gzip -dc "$f" > "$sources"
done

for POOL in pool/"$VERSION"/*/binary ; do
  CODENAME=`echo "$POOL"|sed 's,.*/\(.*\)/binary$,\1,'`
  case $CODENAME in
  *stable) ;;
  *)
    arch_list='i386 amd64'
    for ARCH in $arch_list ; do
      ARCHDIR=dists/$CODENAME/main/binary-$ARCH
      mkdir -p "$ARCHDIR"

      dpkg-scanpackages -a "$ARCH" "$POOL" /dev/null > "$ARCHDIR/Packages"
      gzip -9 < "$ARCHDIR/Packages" > "$ARCHDIR/Packages.gz" 
      bzip2 -9 < "$ARCHDIR/Packages" > "$ARCHDIR/Packages.bz2"
    done

    RELEASE=dists/$CODENAME/Release
    rm -f "$RELEASE" "$RELEASE.gpg"
    apt-ftparchive \
	-oAPT::FTPArchive::Release::Origin=Xapian \
	-oAPT::FTPArchive::Release::Label=Xapian \
	-oAPT::FTPArchive::Release::Components=main \
	-oAPT::FTPArchive::Release::Architectures="$arch_list" \
	-oAPT::FTPArchive::Release::Codename="$CODENAME" \
	release "dists/$CODENAME" > Release.tmp
    mv Release.tmp "$RELEASE"
    gpg -u 'www.xapian.org/debian repo signing key' -abs -o "$RELEASE.gpg" "$RELEASE"
  esac
done
#rsync -v -a pool/"$VERSION" ixion.tartarus.org:/usr/data/www/xapian.org/debian/pool
#rsync -v -a dists/ ixion.tartarus.org:/usr/data/www/xapian.org/debian/dists
