/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gnome.h>

#include "interface.h"
#include "support.h"

#include "display.h"

int
main (int argc, char *argv[])
{
  GtkWidget *indexergui;

  gnome_init ("indexergui", VERSION, argc, argv);

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  indexergui = create_indexergui ();
  init_indexergui(indexergui);
  /*
  init_canvas(GNOME_CANVAS(gtk_object_get_data(GTK_OBJECT(indexergui),
						"canvas1")));
						*/
  gtk_widget_show (indexergui);

  gtk_main ();
  return 0;
}

